#!/bin/bash
cd /home/hari/toddler

comm -2 -3 <(sort ./data/u2c) <(sort ./data/ucd)|grep -vf data/buggers| head -2|\
  while read url; do
    echo $$ > run.pid
    echo "--------------------------------------------------------------------------------" >> out/crawl.out
    echo $url
    echo "--------------------------------------------------------------------------------" >> out/crawl.out
    echo `date` >> out/crawl.out
    phantomjs src/crawl.js $url >> out/crawl.out
    (grep -e '\[RESULT\]' ./out/crawl.out |sort|uniq|sed -e 's/\s\s*/ /g'|awk -F "]" '{print $3}'|sed -e 's/\[//g' -e 's/\s//g'|sort|uniq) > ./data/ucd
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^" >> out/crawl.out
  done


  echo "Done"
